### ISSUE TITLE
Connex PIS Font

### ISSUE THREAD

**Issue by MatthewK421** [davwheat/raildotmatrix.co.uk#21]
[connex-pis-board-clock.zip](https://github.com/davwheat/uk-dot-matrix/files/13767292/connex-pis-board-clock.zip)
[connex-pis-board-info.zip](https://github.com/davwheat/uk-dot-matrix/files/13767293/connex-pis-board-info.zip)

**Comment by davwheat** [comment]
[font.zip](https://github.com/davwheat/uk-dot-matrix/files/13767323/font.zip)
